import twilio from 'twilio';
import { EventEmitter } from 'events';
import { logOut, logError } from '../utils/logger.js';
import VoiceResponse from 'twilio/lib/twiml/VoiceResponse.js';
import { CachedAssetsService } from './CachedAssetsService.js';
import { ConversationRelayConfig } from '../interfaces/ConversationRelay.js';
import { ServerConfig } from '../config/ServerConfig.js';

/**
 * Interface for status callback object
 */
interface StatusCallback {
    CallSid: string;
    [key: string]: any;
}

/**
 * Service class for handling Twilio-related operations including making calls and generating TwiML for the Conversation Relay service.
 *
 * ## Usage Guidelines
 *
 * **Use TwilioService when:**
 * - Making complex API calls that use multiple Twilio services
 * - Implementation requires non-API level business logic
 * - NOT creating an LLM tool (tools should be self-contained)
 *
 * **Don't use TwilioService (use direct Twilio API) when:**
 * - Creating LLM tools in src/tools/ directory
 * - Tools should call Twilio API directly for self-contained execution
 * - Example: src/tools/send-sms.ts uses direct twilio.messages.create() call
 *
 * @class
 * @property {string} accountSid - Twilio account SID from environment variables
 * @property {string} authToken - Twilio authentication token from environment variables
 * @property {string} fromNumber - Twilio phone number to use as the sender
 * @property {twilio.Twilio} twilioClient - Initialized Twilio client instance
 */
class TwilioService extends EventEmitter {
    private accountSid: string;
    private authToken: string;
    private fromNumber: string;
    private twilioClient: twilio.Twilio;

    constructor(config: ServerConfig) {
        super();

        // Config is required - no fallbacks
        // ServerConfig.fromEnv() already validated these exist
        this.accountSid = config.twilioAccountSid;
        this.authToken = config.twilioAuthToken;
        this.fromNumber = config.twilioFromNumber;

        const edge = config.twilioEdge;
        const region = config.twilioRegion;

        // Initialize Twilio client with optional edge location configuration
        if (edge && region) {
            logOut('TwilioService', `Initializing with Edge: ${edge}, Region: ${region}`);
            this.twilioClient = twilio(this.accountSid, this.authToken, { edge, region });
        } else {
            logOut('TwilioService', 'Initializing with default Twilio routing (no edge/region specified)');
            this.twilioClient = twilio(this.accountSid, this.authToken);
        }
    }

    /**
     * Initialize the service
     */
    async initialize(): Promise<void> {
        logOut('TwilioService', 'TwilioService initialized');
    }

    /**
     * Helper function to filter out unset values from configuration
     */
    private filterUnsetValues(config: any): any {
        const filtered: any = {};

        Object.entries(config).forEach(([key, value]) => {
            if (value !== null && value !== undefined && value !== '' &&
                !(Array.isArray(value) && value.length === 0)) {
                filtered[key] = value;
            }
        });

        return filtered;
    }

    /**
     * Makes an outbound call and connects it to the Conversation Relay service.
     * The call is automatically recorded and uses TwiML generated by connectConversationRelay.
     *
     * @param {string} serverBaseUrl - Base URL for the Conversation Relay WebSocket server (without wss:// prefix)
     * @param {string} toNumber - The destination phone number in E.164 format
     * @param {CachedAssetsService} cachedAssetsService - Service for accessing configuration
     * @param {Record<string, string>} parameters - Optional parameters to pass to Conversation Relay
     * @returns {Promise<any>} The Twilio call object if successful
     * @throws {Error} If the call cannot be initiated or other Twilio API errors occur
     */
    async makeOutboundCall(serverBaseUrl: string, toNumber: string, cachedAssetsService: CachedAssetsService, parameters?: Record<string, string>): Promise<any> {
        try {
            const conversationRelay = await this.connectConversationRelay(serverBaseUrl, cachedAssetsService, parameters);

            if (!conversationRelay) {
                throw new Error('Failed to generate TwiML for conversation relay');
            }

            const call = await this.twilioClient.calls.create({
                to: toNumber,
                from: this.fromNumber,
                twiml: conversationRelay,
                record: true,
            });

            logOut('TwilioService', `Made a call from: ${this.fromNumber} to: ${toNumber}`);
            return call;

        } catch (error) {
            logError('TwilioService', `Make Outbound call error: ${error instanceof Error ? error.message : String(error)}`);
            throw error;
        }
    }

    /**
     * Generates TwiML to connect a call to the Conversation Relay service.
     * Uses dynamic configuration from CachedAssetsService instead of hardcoded values.
     * Can be used for both inbound and outbound calls.
     *
     * @param {string} serverBaseUrl - Base URL for the Conversation Relay WebSocket server (without wss:// prefix)
     * @param {CachedAssetsService} cachedAssetsService - Service for accessing configuration
     * @param {Record<string, string>} parameters - Optional parameters to pass to Conversation Relay (e.g., callReference, contextKey, manifestKey)
     * @returns {Promise<twilio.twiml.VoiceResponse|null>} The TwiML response object if successful, null if generation fails
     */
    async connectConversationRelay(serverBaseUrl: string, cachedAssetsService: CachedAssetsService, parameters?: Record<string, string>): Promise<twilio.twiml.VoiceResponse | null> {
        try {
            logOut('TwilioService', `Generating TwiML for call with parameters: ${JSON.stringify(parameters || {})}`);

            // Get configuration from CachedAssetsService
            const config = cachedAssetsService.getConversationRelayConfig();
            const languages = cachedAssetsService.getLanguages();

            if (!config) {
                logError('TwilioService', 'No ConversationRelay configuration found');
                return null;
            }

            // Generate the TwiML with dynamic configuration
            const response: VoiceResponse = new twilio.twiml.VoiceResponse();
            const connect: VoiceResponse.Connect = response.connect();
            const filteredConfig = this.filterUnsetValues(config);

            // Extract languages and parameters before spreading config
            // These should only be child elements, not attributes
            const { languages: configLanguages, parameters: configParameters, ...conversationRelayAttributes } = filteredConfig;

            const conversationRelay: VoiceResponse.ConversationRelay = connect.conversationRelay({
                url: `wss://${serverBaseUrl}/conversation-relay`,
                ...conversationRelayAttributes
            } as any);

            // Add language configurations if available
            if (languages) {
                Object.keys(languages).forEach(langCode => {
                    const langConfig = languages[langCode];
                    if (langConfig && langConfig.ttsProvider && langConfig.voice) {
                        conversationRelay.language({
                            code: langCode,
                            ttsProvider: langConfig.ttsProvider,
                            voice: langConfig.voice,
                        });
                    }
                });
            }

            // Add all parameters dynamically
            if (parameters) {
                Object.entries(parameters).forEach(([name, value]) => {
                    conversationRelay.parameter({
                        name,
                        value
                    });
                });
            }

            // logOut('TwilioService', `Generated TwiML using Helper for call: ${response.toString()}`);

            return response;

        } catch (error) {
            logError('TwilioService', `Error generating call TwiML: ${error instanceof Error ? error.message : String(error)}`);
            return null;
        }
    }


    /**
     * Evaluate the status callback received. This will be used in the LLM to determine the next steps.
     * If there is nothing to be done, just null the response.
     * 
     * @param statusCallback - The status callback object from Twilio
     * @returns The evaluated status callback object or null
     */
    async evaluateStatusCallback(statusCallback: StatusCallback): Promise<StatusCallback | null> {
        try {
            logOut('TwilioService', `Evaluating status callback: ${JSON.stringify(statusCallback)}`);
            // Do something and then emit the event type
            const callSid = statusCallback.CallSid;
            logOut('TwilioService', `Returning evaluated status callback for callSid: ${callSid}`);
            return statusCallback;
        } catch (error) {
            logError('TwilioService', `Error evaluating status callback: ${error instanceof Error ? error.message : String(error)}`);
            return null;
        }
    }
}

export { TwilioService };
